# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homework_api' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for homework_api
  pod 'Alamofire', '~> 5.4'
  pod 'KakaoSDK'
  pod 'SwiftyJSON'
end
